DROP DATABASE lms;
CREATE DATABASE lms;
\c lms;

CREATE TABLE DEPARTMENT(
  DEP_ID  BIGSERIAL PRIMARY KEY     NOT NULL,
  DEP_NAME  VARCHAR NOT NULL
);


CREATE TABLE USERH(
  USERID  BIGSERIAL PRIMARY KEY     NOT NULL,
  NAME           TEXT    NOT NULL,
  EMAIL  VARCHAR (50),
  ROLE VARCHAR NOT NULL,
  DEP_ID INT    NOT NULL  REFERENCES DEPARTMENT(DEP_ID)

);

CREATE TABLE FOODORDER(

  ORDERID  SERIAL PRIMARY KEY ,
  DATE VARCHAR(50)  NOT NULL ,
  USERID INT  NOT NULL REFERENCES USERH(USERID),
  PROVIDERID    INT  NOT NULL,
  MEAL     VARCHAR(50)   NOT NULL,
  QUANTITY INT ,
  AMOUNT INT 
  

);

CREATE TABLE LEAVE(

  USERID INT    NOT NULL  REFERENCES USERH(USERID) ,
  LEAVEDATE           DATE  NOT NULL,
  LEAVETYPE           VARCHAR   NOT NULL,
  REASON VARCHAR (50),
  COMMENT VARCHAR (100),
  PRIMARY KEY(USERID,LEAVEDATE)

);


CREATE TABLE GROUPS(

  GROUPID BIGSERIAL PRIMARY KEY  NOT NULL,
  GROUPNAME     VARCHAR NOT NULL,
  GROUPLEDERID  INT  NOT NULL  REFERENCES USERH(USERID)

);

CREATE TABLE USEROFGROUP(

  USERID INT    NOT NULL  REFERENCES USERH(USERID) ,
  GROUPID INT   NOT NULL  REFERENCES GROUPS(GROUPID)
  ON DELETE CASCADE,
  PRIMARY KEY(USERID,GROUPID)

);

CREATE TABLE FEEDBACK(
  FEEDBACKID  BIGSERIAL PRIMARY KEY NOT NULL,
  USERID INT    NOT NULL  REFERENCES USERH(USERID) ,
  PROVIDERID INT   NOT NULL  ,
  MEAL VARCHAR(100) NOT NULL ,
  FEEDBACK VARCHAR(199) NOT NULL
);

CREATE TABLE MEAL(
  MEALID  BIGSERIAL PRIMARY KEY NOT NULL,
  MEALNAME VARCHAR(100) NOT NULL  ,
  PROVIDERID INT   NOT NULL  ,
  PRICE INT NOT NULL
);



INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('CTO');
INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('Delivery');
INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('Go to Market');
INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('Kandy Team');
INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('Incubator Unit');
INSERT INTO DEPARTMENT(DEP_NAME) VALUES ('Support');

\copy userh(name,email,role,dep_id) FROM 'userh.csv' DELIMITER ',' CSV HEADER;
commit;
